---
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm format

      - name: Build project
        run: pnpm run build

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Generate semantic version
        id: semver
        run: |
          RUN_NUMBER=${GITHUB_RUN_NUMBER}
          MAJOR=$((RUN_NUMBER / 100))
          MINOR=$(((RUN_NUMBER % 100) / 10))
          PATCH=$((RUN_NUMBER % 10))
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Calculated version: $VERSION (from run #$RUN_NUMBER)"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REPO_LC }}:latest
            ${{ env.REPO_LC }}:${{ env.VERSION }}
            ${{ env.REPO_LC }}:${{ env.VERSION }}-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
